# Generated by Django 2.1.2 on 2018-10-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(help_text='Идентификатор ответа', primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, help_text='Ответ', null=True)),
            ],
            options={
                'ordering': ['-id', 'answer'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(help_text='Идентификатор вопроса', primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, help_text='Вопрос', null=True)),
                ('answer_id', models.ForeignKey(help_text='Идентификатор ответа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faq.Answer')),
            ],
            options={
                'ordering': ['-answer_id', '-id', 'question'],
            },
        ),
    ]
