# Generated by Django 2.1.2 on 2018-10-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, help_text='Идентификатор ответа')),
                ('answer', models.TextField(blank=True, help_text='Ответ', null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-id', 'answer']},
        ),

        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, help_text='Идентификатор вопроса')),
                ('question', models.TextField(blank=True, help_text='Вопрос', null=True)),
                ('answer_id', models.ForeignKey('Answer', on_delete=models.SET_NULL, null=True, help_text='Идентификатор ответа')),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-answer_id', '-id', 'question']},
        ),
    ]
