version: '3'
services:

    db:
      container_name: "postgres"
      image: postgres
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/
        - ./postgres/dump:/dump
        - ./postgres/init:/init

    nginx:
        container_name: "nginx"
        image: nginx
        restart: always
        environment:
          #- NGINX_HOST
          - NGINX_PORT=80
        ports:
          - "80:80"
        volumes:        
          - ./app:/docker_app
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - app
        
    app:
        container_name: "app"
        build: ./app
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./app:/docker_app
        depends_on:
          - db

volumes:
    pgdata:

