version: '3'
services:

    db:
      container_name: "postgres"
      image: postgres
      environment:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_NAME
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: "nginx"
        build: ./nginx
        restart: always
        environment:
          #- NGINX_HOST
          - NGINX_PORT=80
        ports:
          - "80:80"
        volumes:        
          - app_data:/docker_app
          - ./log:/var/log/nginx
        depends_on:
          - app
        
    app:
        container_name: "app"
        build: ./app
        restart: always
        #command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        volumes:
          - app_data:/docker_app
        depends_on:
          - db

volumes:
    app_data:
    pgdata:

